[build]
builder = "NIXPACKS"

[deploy]
# autorise jusqu'à 45 min (2 700 s) pour le build
timeoutSeconds = 2700
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3 

[healthcheck]
path = "/api"
interval = 30
timeout = 10
maxRetries = 3 