[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
cronCommand = "npm run cron"

[healthcheck]
path = "/api"
interval = 30
timeout = 10
maxRetries = 3 